# Generated by Django 5.0.3 on 2024-03-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='Are you a writer?'),
        ),
    ]
